image: alpine

pages:
  script:
  - apk --no-cache add py-pip
  - pip install sphinx sphinx_rtd_theme
  - apk --no-cache add make
  - make -C docs html
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
